---
resource_types:
- name: rsync-resource
  type: docker-image
  source:
      repository: mrsixw/concourse-rsync-resource
      tag: latest

resources:
- name: my-product
  type: git
  source:
    uri: git@github.com:RyanDur/contract-testing.git
    branch: master
    private_key: {{my-product-github-private-key}}

- name: sync-resource
  type: rsync-resource
  source:
    server: 10.0.0.5
    base_dir: ~/home/shared
    user: root
    private_key: {{my-product-github-private-key}}

jobs:
- name: unit
  plan:
  - get: my-product
    trigger: true
  - task: unit
    file: my-product/ci/unit.yml

- name: build-rc
  serial_groups: [version]
  plan:
  - get: my-product
    passed: [unit]
    trigger: true
  - task: build-artifact
    file: my-product/ci/build-artifact.yml
  - put: sync-resource
    params: {"my-product/producer/build/libs/producer-1.0-SNAPSHOT.jar" : "~/home/shared" }