---
resource_types:
- name: rsync-resource
  type: docker-image
  source:
      repository: mrsixw/concourse-rsync-resource
      tag: latest

resources:
- name: my-product
  type: git
  source:
    uri: git@github.com:RyanDur/contract-testing.git
    branch: master
    private_key: {{my-product-github-private-key}}

- name: sync-resource
  type: rsync-resource
  source:
    server: server
    base_dir: /sync_directory
    user : user
    private_key: {{s3-secret-access-key}}

jobs:
- name: unit
  plan:
  - get: my-product
    trigger: true
  - task: unit
    file: my-product/ci/unit.yml

- name: build-rc
  serial_groups: [version]
  plan:
  - get: my-product
    passed: [unit]
    trigger: true
  - task: build-artifact
    file: my-product/ci/build-artifact.yml
  - put: sync-resource
    params: {"sync_dir" : "my_output_dir" }
  - put: sync-resource
    params: {
      "sync_dir" : "my_output_dir",
      "rsync_opts": ["-Pav", "--del", "--chmod=Du=rwx,Dgo=rx,Fu=rw,Fog=r"]
    }